Nombre=nivel1
# CajaNNN=[Nombre],[Simbolo],[Instancias],[PosX],[PosY]
Caja1=Flores,F,3,23,5
Caja2=Hongos,H,2,7,4
Caja3=Caramelos,C,4,21,2
Plataforma=127.0.0.1:5000
TiempoChequeoDeadlock=10000
Recovery=1
Enemigos=3
Sleep_Enemigos=2000
algoritmo=RR
quantum=3
retardo=500
LOG_PATH=/tmp/nivel.log
LOG_NIVEL=DEBUG
LOG_CONSOLA=1
