DIR = Commons Parser Kernel Programa UMV Cpu

all: $(DIR)

$(DIR):
	@echo ' '
	@echo '----------------------------------------------'
	@echo '      Compilo el proceso $@:'
	@echo '----------------------------------------------'
	$(MAKE) -C $@
.PHONY: $(DIR)
